# Generated by Django 4.2.23 on 2025-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(default=(2026, 8, 6)),
            preserve_default=False,
        ),
    ]
