# Generated by Django 4.2.23 on 2025-08-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_employee_contract_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract_end_date',
        ),
    ]
